/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IAvarikSagaInterface extends ethers.utils.Interface {
  functions: {
    "addToPresaleList(address[],uint256[])": FunctionFragment;
    "buy(uint256)": FunctionFragment;
    "presaleBuy(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addToPresaleList",
    values: [string[], BigNumberish[]]
  ): string;
  encodeFunctionData(functionFragment: "buy", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "presaleBuy",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "addToPresaleList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "buy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "presaleBuy", data: BytesLike): Result;

  events: {};
}

export class IAvarikSaga extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IAvarikSagaInterface;

  functions: {
    addToPresaleList(
      entries: string[],
      maxAmounts: BigNumberish[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "addToPresaleList(address[],uint256[])"(
      entries: string[],
      maxAmounts: BigNumberish[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    buy(
      tokenQuantity: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "buy(uint256)"(
      tokenQuantity: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    presaleBuy(
      tokenQuantity: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "presaleBuy(uint256)"(
      tokenQuantity: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;
  };

  addToPresaleList(
    entries: string[],
    maxAmounts: BigNumberish[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "addToPresaleList(address[],uint256[])"(
    entries: string[],
    maxAmounts: BigNumberish[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  buy(
    tokenQuantity: BigNumberish,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "buy(uint256)"(
    tokenQuantity: BigNumberish,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  presaleBuy(
    tokenQuantity: BigNumberish,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "presaleBuy(uint256)"(
    tokenQuantity: BigNumberish,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  callStatic: {
    addToPresaleList(
      entries: string[],
      maxAmounts: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    "addToPresaleList(address[],uint256[])"(
      entries: string[],
      maxAmounts: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    buy(tokenQuantity: BigNumberish, overrides?: CallOverrides): Promise<void>;

    "buy(uint256)"(
      tokenQuantity: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    presaleBuy(
      tokenQuantity: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "presaleBuy(uint256)"(
      tokenQuantity: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    addToPresaleList(
      entries: string[],
      maxAmounts: BigNumberish[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "addToPresaleList(address[],uint256[])"(
      entries: string[],
      maxAmounts: BigNumberish[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    buy(
      tokenQuantity: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "buy(uint256)"(
      tokenQuantity: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    presaleBuy(
      tokenQuantity: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "presaleBuy(uint256)"(
      tokenQuantity: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addToPresaleList(
      entries: string[],
      maxAmounts: BigNumberish[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "addToPresaleList(address[],uint256[])"(
      entries: string[],
      maxAmounts: BigNumberish[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    buy(
      tokenQuantity: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "buy(uint256)"(
      tokenQuantity: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    presaleBuy(
      tokenQuantity: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "presaleBuy(uint256)"(
      tokenQuantity: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;
  };
}
