/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IAvarikSaga } from "../IAvarikSaga";

export class IAvarikSaga__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAvarikSaga {
    return new Contract(address, _abi, signerOrProvider) as IAvarikSaga;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address[]",
        name: "entries",
        type: "address[]",
      },
      {
        internalType: "uint256[]",
        name: "maxAmounts",
        type: "uint256[]",
      },
    ],
    name: "addToPresaleList",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenQuantity",
        type: "uint256",
      },
    ],
    name: "buy",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenQuantity",
        type: "uint256",
      },
    ],
    name: "presaleBuy",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
];
